site_name: Rank-CN铁锈排位官方文档
site_description: "Rank-CN"
site_author: "幻想"
copyright: "Copyright &copy; 2024 幻想"

theme:
  site_author: '幻想'
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  i18n:
    prev: 'Previous'
    next: 'Next'
  features:
# 进度指示器
    - navigation.instant
    - navigation.instant.progress
# 导航路径面包屑
    - navigation.path
# 返回顶部按钮
    - navigation.top
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    #- navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

plugins:
    - search #搜索配置

repo_url: https://xmrank.someo.top
repo_name: "前往Rank-CN官网"

nav:
  - '首页': "index.md"
  - '账号系统': "account"
  - '命令功能（未写完）': "command"
  - '组队开黑': "teams"
  - '队伍相关': "account"
  - '机制相关（未写完）': "mechanism"
  - '语音功能': "phone"
  - '举报功能': "report"
  - '其他服务（未写完）': "other"
  - '帮助与支持（未写完）': "about.md"