site_name: Rank-CN铁锈排位官方文档
site_description: "Rank-CN铁锈战争游戏排位官方文档"
site_author: "幻想"
copyright: "Copyright &copy; 2024 幻想"

theme:
  site_author: '幻想'
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  i18n:
    prev: 'Previous'
    next: 'Next'
  features:
# 即时加载
    - navigation.instant
# 进度指示器
    - navigation.instant
    - navigation.instant.progress
# 导航路径面包屑
    - navigation.path
# 返回顶部按钮
    - navigation.top

plugins:
    - search # necessary for search to work

repo_url: https://xmrank.someo.top
repo_name: "前往Rank-CN官网"

palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到黑暗模式

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到白天模式

nav:
  - '首页': "index.md"
  - '账号系统': "account"
  - '关于': "about.md"